
CREATE USER saraa IDENTIFIED BY 'password';

GRANT ALL PRIVILEGES ON saraa2_db.* TO saraa;

FLUSH PRIVILEGES;

CREATE USER gitea IDENTIFIED BY 'gitea';

GRANT ALL PRIVILEGES ON gitea.* TO gitea;

FLUSH PRIVILEGES;